### ISSUE TITLE
The SDP does not match the previously generated SDP for this type

### ISSUE THREAD

**Issue by Zibri** [fippo/sdp-minimizer#4]
it does not work...
I mean your program works, but then the rtc connection does not:

Failed to execute 'setLocalDescription' on 'RTCPeerConnection': The SDP does not match the previously generated SDP for this type

**Comment by fippo** [comment]
You are not supposed to use this with setLocalDescription, that takes the original SDP.

**Comment by Zibri** [comment]
yep.. I solved that anyway... but the connection does not go thru... no errors now.. with the original sdp it works. (p.s. I am using google ice servers but I don't think that's the problem)
